# Copyright (c) 2021 by the Zeek Project. See LICENSE for details.

# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_UDP
# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_UDP_HMAC_MD5
# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_UDP_HMAC_SHA1
# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_UDP_HMAC_SHA256
# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_UDP_HMAC_SHA512
# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_TCP
# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_TCP_HMAC_MD5
# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_TCP_HMAC_SHA1
# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_TCP_HMAC_SHA256
# @TEST-EXEC: ${ZEEK} -NN | grep -q ANALYZER_SPICY_OPENVPN_TCP_HMAC_SHA512
#
# @TEST-DOC: Check that OpenVPN analyzer is available.
