#! /bin/sh

base=$(cd $(dirname $0)/.. && pwd)

if [ "$1" = "--plugin-path" ]; then
    # 1. Explicit override
    test -n "${SPICY_ZEEK_PLUGIN_PATH}" && echo "${SPICY_ZEEK_PLUGIN_PATH}" && exit 0

    # 2. Check for local build
    dir=$(${base}/Scripts/build-directory)
    test -d ${dir} && test -f ${dir}/__bro_plugin__ && echo ${dir} && exit 0

    # 3. Check for in Spicy in-tree build
    dir=$(${base}/Scripts/build-directory)/zeek/spicy-plugin
    test -d ${dir} && echo ${dir} && exit 0

    # 4. Use Zeek default
    ${base}/Scripts/run-zeek-config --plugin_dir || exit 1
    exit 0

elif [ "$1" = "--plugin-path-for-installation" ]; then
    # 1. Explicit override
    test -n "${SPICY_INSTALLATION_DIRECTORY}" && ls -d ${SPICY_INSTALLATION_DIRECTORY}/lib*/zeek-spicy && exit 0

    # 2. Derive from Spicy prefix
    ls -d $(${base}/Scripts/run-spicy-config --prefix)/lib*/zeek-spicy 2>/dev/null && exit 0

    # 3. If we have spicyz in path, derive from module path.
    spicyz=$(which spicyz 2>/dev/null)
    test -n "${spicyz}" && echo $(cd $(${spicyz} --print-plugin-path) && pwd) && exit 0

    exit 1

elif [ "$1" = "--zeek-path" ]; then
    # 1. Explicit override
    test -n "${ZEEKPATH}" && echo "${ZEEKPATH}" && exit 0

    # 2. Use Zeek default plus local repository
    echo ${base}/..:$(${base}/Scripts/run-zeek-config --zeekpath)

    exit 0

elif [ "$1" = "--zeek-plugin-path" ]; then
    # Return our plugin path + zkg path + standard Zeek path
    echo $($0 --plugin-path):$(zkg config plugin_dir):$(${base}/Scripts/run-zeek-config --plugin_dir)
    exit 0

elif [ "$1" = "--sh-path" ]; then
    # Combine:
    #   1. test scripts
    #   2. Plugin /bin directory
    #   3. Spicy's /bin directory
    #   4. Zeek's /bin directory
    echo ${base}/Scripts:$($0 --plugin-path)/../../bin:$(${base}/Scripts/run-spicy-config --bindir):$(${base}/Scripts/run-zeek-config --prefix)/bin
    exit 0

elif [ "$1" = "--sh-path-for-installation" ]; then
    plugin_bin="$($0 --plugin-path-for-installation)/../../bin"
    zeek_config="$(${plugin_bin}/spicyz --print-zeek-config)"

    # 1. Explicit override for prefix
    prefix="${SPICY_INSTALLATION_DIRECTORY}"

    # 2. Use Spicy prefix
    test -z "${prefix}" && prefix="$(${base}/Scripts/run-spicy-config --prefix)"

    # Combine:
    #   1. test scripts,s
    #   3. Spicy's installation /bin directory (which also holds spicyz)
    #   4. Zeek's /bin directory
    echo ${base}/Scripts:${prefix}/bin:$(${zeek_config} --prefix)/bin
    exit 0

elif [ "$1" = "--module-path" ]; then
    # 1. Explicit override
    test -n "${SPICY_MODULE_PATH}" && echo "${SPICY_MODULE_PATH}" && exit 0

    # 2. Check for local build
    dir=$(${base}/Scripts/build-directory)/spicy-modules
    test -d ${dir} && echo ${dir} && exit 0

    # 3. Check for in Spicy in-tree build
    dir=$(${base}/Scripts/build-directory)/zeek/spicy-analyzers/spicy-modules
    test -d ${dir} && echo ${dir} && exit 0

    exit 1
else
    echo "usage: $(basename $0) --plugin-path{,for-installation} | --zeek-{plugin-}path | --sh-path{,for-installation} | --module-path"
    exit 1
fi
