#! /bin/bash

base=$(cd $(dirname $0)/.. && pwd)

test -n "${ZEEK_CONFIG}" && exe="${ZEEK_CONFIG}"
test -z "${exe}" && exe=$(${base}/Scripts/run-spicy-config --zeek | sed 's#/zeek$#/zeek-config#')

${exe} $@
