#! /bin/sh

base=$(cd $(dirname $0)/.. && pwd)

# 1. Explicit override through environment.
test -n "${SPICY_CONFIG}" && exe="${SPICY_CONFIG}"

# 2. Take from explicitly specified installation.
test -z "${exe}" && test -n "${SPICY_INSTALLATION_DIRECTORY}" && exe="${SPICY_INSTALLATION_DIRECTORY}/bin/spicy-config"

# 3. Try local in-tree build directory.
x=$(${base}/Scripts/build-directory)/bin/spicy-config
test -z "${exe}" && test -x "${x}" && exe="${x}"

# 4. Whatever CMake discovered.
if [ -z "${exe}" -a -f "$(${base}/Scripts/build-directory)/CMakeCache.txt" ]; then
    cached=$(cat $(${base}/Scripts/build-directory)/CMakeCache.txt | grep ^SPICY_CONFIG: | cut -d '=' -f 2)
    test -n "${cached}" && exe=${cached}
fi

# 5. Take what's in PATH.
test -z "${exe}" && exe="$(which spicy-config 2>/dev/null)"

if [ -z "${exe}" -o ! -x "${exe}" ]; then
    test -n "${SPICY_INSTALLATION_DIRECTORY}" || echo "cannot find spicy-config; make sure it is in PATH or set SPICY_CONFIG" >&2
    exit 1
fi

exec ${exe} $@
