#! /bin/sh

base=$(cd $(dirname $0)/.. && pwd)

# 1. Explicit override through environment.
test -n "${ZEEK_CONFIG}" && exe="${ZEEK_CONFIG}"

# 2. If we're running from the installation, ask spicyz.
if [ -z "${exe}" -a -n "${SPICY_INSTALLATION_DIRECTORY}" ]; then
    plugin_bin="$(${base}/Scripts/get-path --plugin-path-for-installation)/../../bin"
    exe="$(${plugin_bin}/spicyz --print-zeek-config)"
fi

# 3. Whatever CMake discovered.
if [ -z "${exe}" -a -f "$(${base}/Scripts/build-directory)/CMakeCache.txt" ]; then
    cached=$(cat $(${base}/Scripts/build-directory)/CMakeCache.txt | grep ^ZEEK_CONFIG: | cut -d '=' -f 2)
    test -n "${cached}" && exe=${cached}
fi

# 4. Take what's in PATH.
test -z "${exe}" && exe="$(which zeek-config 2>/dev/null)"

if [ -z "${exe}" -o ! -x "${exe}" ]; then
    test -n "${SPICY_INSTALLATION_DIRECTORY}" || echo "cannot find zeek-config; make sure it is in PATH or set ZEEK_CONFIG" >&2
    exit 1
fi

exec ${exe} $@
