#! /bin/sh
#
# Wrapper around Zeek to set environment.

if [ "${SPICY_ZKG}" = "1" ]; then
   unset ZEEKPATH
   unset ZEEK_PLUGIN_PATH
fi

zeek="$(spicy-config --zeek) -G $(dirname $0)/../random.seed"
LD_PRELOAD=${ZEEK_LD_PRELOAD} DYLD_INSERT_LIBRARIES=${ZEEK_LD_PRELOAD} ASAN_OPTIONS=detect_leaks=0:detect_odr_violation=0 ${zeek} $@
